name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build_and_release:
    name: Build & Release RDM
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build
        run: make dmg
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RDM.dmg
            RDM.pkg
          generate_release_notes: true
          name: RDM ${{ env.RELEASE_VERSION }}